version: '3'

services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: exemplo-generic-dao
    ports:
      - '5432:5432'
